### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by SubZero1993** [nccgroup/freddy#2] opened 2018-06-11 16:52 UTC
After some time of scanning the Java garbage collector drops an out of memory exception, probably because of an active scan:

java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.cb.a(Unknown Source)
	at burp.xcf.makeHttpRequest(Unknown Source)
	at burp.z3f.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:802)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:428)
	at burp.jtc.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vdbaan** [comment] 2018-08-14 08:55
Hi SubZero1993,

can you provide a little bit more info on what happened (CPU type, total memory, burp launch parameters, number of active scan threads, number of items in queue, etc). I am trying to reproduce this issue, but am unable to do so.

Thanks in advance,
S.

**Comment by SubZero1993** [comment] 2018-08-16 13:36
Sry for the late response!

OS: Debian 9 x64 with the latest updates
CPU Type: x86_64 - Dual Intel X5650
Memory: 16GB
Burp Parameters: java -Xmx12g -jar ...
Scan Threads: 32
Items in Queue: ~ a few thousand 

I was curious and wanted to test how much I'm able to stress the machine with scanning our University network on different types of web services all at once and how our WAF handles this kind of attacks. 
Some weeks ago I saw an update in the BApp Store for Freddy and that fixed the problem I guess. The machine never slowed down as much as it did before the update. I keep on testing that and if I've more information I'll let you know.

**Comment by vdbaan** [comment] 2018-08-16 15:39
No problem.

Thanks for the update. It could have been a combination of the updates of the plugin and Burp itself that fixed it as I can't reproduce the error. I am using similar settings and even with 50 concurrent threads I do not get an error.
If you are ok with it, I would like to close this issue.

**Closed as completed** 2018-08-16 16:19 UTC
